<?php
$conn = new mysqli("localhost", "root", "", "SocialMediaDB");

// create user_profiles table
$conn->query("DROP TABLE IF EXISTS posts");
$conn->query("DROP TABLE IF EXISTS user_profiles");
$conn->query("
    CREATE TABLE user_profiles (
        id        INT PRIMARY KEY AUTO_INCREMENT,
        username  VARCHAR(50)  NOT NULL UNIQUE,
        password  VARCHAR(255) NOT NULL,
        full_name VARCHAR(100) NOT NULL
    )
");

// users with plaintext passwords (randomly generated by Claude.ai)
$users = [
['u001', 'bhayes',     'X9$kLm2!Rp',    'Brandon Hayes'],
['u002', 'cnguyen',    'Qw7#Tz4!Vn',    'Cleopatra Nguyen'],
['u003', 'fokafor',    'Jb3$Wy8!Ks',    'Felix Okafor'],
['u004', 'hkobayashi', 'Nd6#Rp1!Xm',    'Hana Kobayashi'],
['u005', 'ipetrov',    'Fv4$Gh9!Lc',    'Ivan Petrov'],
['u006', 'jmorrison',  'Bt2#Kq7!Yw',    'Jade Morrison'],
['u007', 'knakamura',  'Zs5$Mn3!Dj',    'Kai Nakamura'],
['u008', 'lcruz',      'Hp8#Vf6!Rb',    'Leonardo Cruz'],
['u009', 'mjohansson', 'Cx1$Wt4!Nk',    'Mia Johansson'],
['u010', 'nbrooks',    'Lg7#Qs2!Fm',    'Nathaniel Brooks'],
['u011', 'obennett',   'Ry3$Jd8!Tz',    'Olivia Bennett'],
['u012', 'pferreira',  'Wm6#Xb5!Vc',    'Paulo Ferreira'],
['u013', 'qellison',   'Kn9$Hp1!Sg',    'Quinn Ellison'],
['u014', 'rdelgado',   'Tz4#Lw7!Qx',    'Rosa Delgado'],
['u015', 'stran',      'Vj2$Rc6!Ym',    'Samuel Tran'],
['u016', 'tsimmons',   'Bf8#Nd3!Wk',    'Tara Simmons'],
['u017', 'udiallo',    'Mx5$Qs9!Jp',    'Umar Diallo'],
['u018', 'vsokolova',  'Gh1#Fz4!Lb',    'Vera Sokolova'],
['u019', 'washford',   'Dn7$Kt2!Xv',    'William Ashford'],
['u020', 'ytanaka',    'Rp3#Cw8!Mj',    'Yuki Tanaka'],
];

// insert each user with a hashed password
$stmt = $conn->prepare("
    INSERT INTO user_profiles (username, password, full_name)
    VALUES (?, ?, ?)
");

foreach ($users as [$username, $plaintext, $full_name]) {
    $hashed = password_hash($plaintext, PASSWORD_BCRYPT);
    $stmt->bind_param("ssss", $username, $hashed, $full_name);
    $stmt->execute();
    echo "Inserted: <strong>$username</strong> &nbsp;✔<br>";
}

$stmt->close();

$conn->close();

echo "<br><br><strong style='color:green;'>Setup complete! For assignment purposes, all of this information is saved in this repository to make everything visible. In real scenarios, this would be deleted for security reasons.</strong>";
?>